// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY12oQ1uBEvUi_FpSRdLqG10WJnatjuDk',
    appId: '1:951617145388:web:0ba957824bd1538afcdf89',
    messagingSenderId: '951617145388',
    projectId: 'salons-e6547',
    authDomain: 'salons-e6547.firebaseapp.com',
    storageBucket: 'salons-e6547.appspot.com',
    measurementId: 'G-8G9TEYZKER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZzjZ98kqRPipg2hXyrXcWRdBc0QonlpY',
    appId: '1:951617145388:android:73b2208b0203061cfcdf89',
    messagingSenderId: '951617145388',
    projectId: 'salons-e6547',
    storageBucket: 'salons-e6547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKUckPloraDTCi1srxETzhi8jWbnNZQM',
    appId: '1:951617145388:ios:82cdb82d25cf0599fcdf89',
    messagingSenderId: '951617145388',
    projectId: 'salons-e6547',
    storageBucket: 'salons-e6547.appspot.com',
    iosClientId: '951617145388-h0jfehi3aoolv7b3obp779fuuiijvuod.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKUckPloraDTCi1srxETzhi8jWbnNZQM',
    appId: '1:951617145388:ios:a923990cec41c19bfcdf89',
    messagingSenderId: '951617145388',
    projectId: 'salons-e6547',
    storageBucket: 'salons-e6547.appspot.com',
    iosClientId: '951617145388-nkoj0lkduge0keiv00rnjt8go63nir78.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonat.RunnerTests',
  );
}
